#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd $HOME
echo "Init submodules"
yadm submodule update --recursive --init

# Rosetta
softwareupdate --install-rosetta

# Ansible
brew install ansible
ansible-galaxy install -r ~/.config/yadm/requirements.yml
ansible-playbook -v ~/.config/yadm/mac-install.yml -i ~/.config/yadm/inventory

# Oh-my-zsh
yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Disable sound effects on boot
sudo nvram StartupMute=%01

# Fonts
sudo cp ~/.config/yadm/fonts/* /Library/Fonts/.

# Allow apps from anywhere
sudo spctl --master-disable
	
# AstroVim
git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim +PackerSync

# Hacky way of storing custom nvim config because of git submodule bs 
cp ~/.config/yadm/sysfiles/init.lua ~/.config/nvim/lua/user/init.lua
ln -f ~/.config/nvim/lua/user/init.lua ~/.config/yadm/sysfiles/init.lua

# Finishing touch
gh auth login
gcloud init
