#!/bin/sh

# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)
cd $HOME
echo "Init submodules"
yadm submodule update --recursive --init

# Rosetta
yes A | softwareupdate --install-rosetta

# Brew & Ansible
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install ansible
ansible-galaxy install -r ~/.config/yadm/requirements.yml
ansible-playbook -vv ~/.config/yadm/mac-install.yml -i ~/.config/yadm/inventory

# Oh-my-zsh
yes | sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Disable sound effects on boot
sudo nvram StartupMute=%01

# Fonts
sudo cp ~/.config/yadm/fonts/* /Library/Fonts/.

# Allow apps from anywhere
sudo spctl --master-disable
	
# AstroVim
git clone https://github.com/AstroNvim/AstroNvim ~/.config/nvim
nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync'

# DISABLED: USING DEFAULT ASTROVIM CONFIG  
# Hacky way of storing custom nvim (AstroVim) config because of git submodule bs 
# mkdir -p ~/.config/nvim/lua/user && cp ~/.config/yadm/sysfiles/init.lua "$_"
# ln -f ~/.config/nvim/lua/user/init.lua ~/.config/yadm/sysfiles/init.lua

# Start Brew services
brew services start autoraise

# Populate locate db, if after this db is still not crated, try "sudo /usr/libexec/locate.updatedb"
sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.locate.plist

# Finishing touch
gh auth login
gcloud init
