---
- name: Mac setup
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3

  #vars_prompt:
  #  - name: mas_email
  #    prompt: "Please input Mac App Store email"
  #    private: no
  #  - name: mas_password
  #    prompt: "Please input Mac App Store password"

  tasks:
    - name: "Homebrew: Install packages & taps"
      community.general.homebrew:
        name:
          - nvim
          #   - koekeishiya/formulae/yabai
          - koekeishiya/formulae/skhd
          - zsh
          - gh
          - thefuck
          - python
          - mas
          - tree
          - sl
          - htop
          - fzf
          - coreutils
          - jq
          - node
          - nv
          - lua
          - moreutils
        state: latest
        update_homebrew: yes

    - name: "Homebrew: Install casks"
      community.general.homebrew_cask:
        name:
          - steam
          - discord
          - spotify
          - kitty
          - homebrew/cask-fonts/font-fira-code
          - google-drive
          - google-cloud-sdk
          - visual-studio-code
          - docker
          - browserosaurus
          - whichspace
        state: latest

    ### mas-cli is currently broken for Monterey+Apple Silicon

    #- name: "Mac App Store: Sign in"
    #  command: 'mas signin "{{ mas_email }}" "{{ mas_password }}"'

    #- name: "Mac App Store: Install apps"
    #  community.general.mas:
    #    id:
    #      - 1548853763 # Singlebox Plus
    #      - # Adguard
    #      - # Agenda
    #      - # 1Password 7
    #      - # Dark Reader for Safari
    #      - # Vimari
    #      - # Agenda
    #      - # Structured
    #    state: latest

    - name: "osx_defaults: Change alert sound from Beep to Blow"
      community.general.osx_defaults:
        domain: com.apple.systemsound
        key: com.apple.sound.beep.sound
        type: string
        value: /System/Library/Sounds/Blow.aiff
        state: present

    - name: "osx_defaults: Disable system Tink sound"
      community.general.osx_defaults:
        domain: com.apple.systemsound
        key: com.apple.sound.uiaudio.enabled
        type: int
        value: 0
        state: present

    - name: "osx_defaults: Decrease key repeat initial delay"
      community.general.osx_defaults:
        key: InitialKeyRepeat
        type: int
        value: 14
        state: present

    - name: "osx_defaults: Decrease delay between key repeats"
      community.general.osx_defaults:
        key: KeyRepeat
        type: int
        value: 1
        state: present

    - name: "osx_defaults: Reduce alert sound volume"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.sound.beep.volume
        type: float

        # Alert volume conversion:
        # 75%: 0.7788008
        # 50%: 0.6065307
        # 25%: 0.4723665
        value: 0.6065307

    - name: "osx_defaults: Disable spaces autoreordering"
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mru-spaces
        type: bool
        value: false
        state: present

    - name: "osx_defaults: Disable mouse acceleration"
      community.general.osx_defaults:
        domain: .GlobalPreferences
        key: com.apple.mouse.scaling
        type: int
        value: -1
        state: present

    ### https://apple.stackexchange.com/questions/59556/is-there-a-way-to-completely-disable-dock

    - name: "osx_defaults: Autohide dock"
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
        state: present

    - name: "osx_defaults: Disable dock, use CMD+D to manually hide/unhide"
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide-delay
        type: float
        value: 1000
        state: present

    - name: "osx_defaults: Disable bounce animation for icons in dock"
      community.general.osx_defaults:
        domain: com.apple.dock
        key: no-bouncing
        type: bool
        value: true
        state: present

    ###
