---
- name: Mac setup
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: "Homebrew: Install packages & taps"
      community.general.homebrew:
        name:
          - nvim
          - zsh
          - gh
          - python
          - mas
          - tree
          - sl
          - htop
          - fzf
          - coreutils
          - jq
          - node
          - lua
          - moreutils
          - gnu-sed
          - rust
          - code-minimap
          - imagemagick
          - pidof
          - neofetch
          - texlive
          - pandoc
          - ripgrep
          - fd
          - thefuck
          - webpack
          - httpie # CLI
        state: latest
        update_homebrew: yes

    - name: "Homebrew: Install casks"
      community.general.homebrew_cask:
        name:
          - steam
          - discord
          - google-cloud-sdk
          - visual-studio-code
          - docker
          - raindropio
          - karabiner-elements
          - raycast
          - sf-symbols
          - linearmouse
          - warp
          - shottr
          - 1password
          - mullvadvpn
          - figma
          - he3-app/he3/he3
          - affinity-designer
          - affinity-photo
          - affinity-publisher
          - postman
          - arc
          - backblaze
        state: latest

    - name: "Pip3: Install packages"
      ansible.builtin.pip:
        name:
          - pywal
        state: latest

    - name: "Mac App Store: Install apps"
      community.general.mas:
        id:
          - 1440147259 # Adguard
          - 1333542190 # 1Password 7
          - 1438243180 # Dark Reader for Safari
          - 937984704 # Amphetamine
        state: latest


    # Mac Defaults
    - name: "osx_defaults: Disable system Tink sound"
      community.general.osx_defaults:
        domain: com.apple.systemsound
        key: com.apple.sound.uiaudio.enabled
        type: int
        value: 0
        state: present
    
    - name: "osx_defaults: Enable Key Repeat"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: ApplePressAndHoldEnabled
        type: bool
        value: false
        state: present

    - name: "osx_defaults: Decrease key repeat initial delay"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: InitialKeyRepeat
        type: int
        value: 15
        state: present

    - name: "osx_defaults: Decrease delay between key repeats"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: KeyRepeat
        type: int
        value: 2
        state: present

    - name: "osx_defaults: Reduce alert sound volume"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.sound.beep.volume
        type: float

        # Alert volume conversion:
        # 75%: 0.7788008
        # 50%: 0.6065307
        # 25%: 0.4723665
        value: 0.6065307

    - name: "osx_defaults: Disable spaces autoreordering"
      community.general.osx_defaults:
        domain: NSGlobalDomain
        key: _HIHideMenuBar
        type: int
        value: 1
        state: present

    - name: "osx_defaults: Autohide menu bar"
      community.general.osx_defaults:
        domain: com.apple.dock
        key: mru-spaces
        type: bool
        value: false
        state: present

    - name: "osx_defaults: Disable mouse acceleration"
      community.general.osx_defaults:
        domain: .GlobalPreferences
        key: com.apple.mouse.scaling
        type: int
        value: -1
        state: present

    ### https://apple.stackexchange.com/questions/59556/is-there-a-way-to-completely-disable-dock

    - name: "osx_defaults: Autohide dock"
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide
        type: bool
        value: true
        state: present

    - name: "osx_defaults: Remove autohide-delay"
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide-delay
        type: float
        # A high value (e.g. 1000) will effectively prevent dock from showing automatically
        value: 0
        state: present

    - name: "osx_defaults: Faster dock show animation"
      community.general.osx_defaults:
        domain: com.apple.dock
        key: autohide-time-modifier
        type: float
        value: 0.15
        state: present

    - name: "osx_defaults: Disable bounce animation for icons with notification in dock"
      community.general.osx_defaults:
        domain: com.apple.dock
        key: no-bouncing
        type: bool
        value: true
        state: present
