#!/usr/bin/env sh

# [SIP] automatically load scripting addition, must perform visudo step first
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  8
yabai -m config bottom_padding               8
yabai -m config left_padding                 8
yabai -m config right_padding                8
yabai -m config window_gap                   8
yabai -m config external_bar                 all:8:0

# mouse settings
yabai -m config mouse_follows_focus          on # on | off
yabai -m config focus_follows_mouse          off # autofocus | autoraise | off

# window settings
yabai -m config window_placement             second_child
yabai -m config auto_balance                 on
yabai -m config split_ratio                  0.50
## border
yabai -m config window_border off
yabai -m config window_border_width 4
yabai -m config active_window_border_color 0xffa05d2c
yabai -m config normal_window_border_color 0xff3f3f3f
##
## opacity
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.25
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95
##
## [SIP] requires sip disabled
yabai -m config window_topmost               on # floating windows always on top
yabai -m config window_shadow                float # disable window shadows
##

# window rules
yabai -m rule --add app="^Music$" display=2 space=3
yabai -m rule --add app="^Microsoft Teams$" display=2 space=3
yabai -m rule --add app="^Discord$" display=2 space=3
yabai -m rule --add app="^System Preferences$" manage=off 
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^1Password$" manage=off

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# auto update from HEAD
brew install yabai --HEAD
