#!/usr/bin/env sh

####################################################################################
# Currently Yabai is setup to start as float, to be used with stage manager
# Mostly used for window rules only. Some Window rules settings require SIP disabled
# Also useful to restart/resize sketchybar on display change
####################################################################################

# [SIP] automatically load scripting addition, must manually perform visudo step to change hash after every Yabai update (maybe OS update too?)
# https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition

###
# sudo visudo -f /private/etc/sudoers.d/yabai
# input the line below into the file you are editing.
# replace <yabai> with the path to the yabai binary (output of: which yabai).
# replace <user> with your username (output of: whoami). 
# replace <hash> with the sha256 hash of the yabai binary (output of: shasum -a 256 $(which yabai)).
# this hash must be updated manually after running brew upgrade.
#
# <user> ALL=(root) NOPASSWD: sha256:<hash> <yabai> --load-sa
###

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# space settings
yabai -m config layout                       bsp # bsp | float
yabai -m config top_padding                  6
yabai -m config bottom_padding               6
yabai -m config left_padding                 6
yabai -m config right_padding                6
yabai -m config window_gap                   6
yabai -m config external_bar                 all:0:0

# mouse settings
yabai -m config mouse_follows_focus          off # on | off
yabai -m config focus_follows_mouse          off # autofocus | autoraise | off

# window settings
yabai -m config window_placement             second_child
yabai -m config auto_balance                 on
yabai -m config split_ratio                  0.50

## border
yabai -m config window_border off
yabai -m config window_border_width 4
yabai -m config active_window_border_color 0xffa05d2c
yabai -m config normal_window_border_color 0xff3f3f3f

## opacity
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.25
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.95

## [SIP] requires sip disabled
yabai -m config window_topmost               off # floating windows always on top
yabai -m config window_shadow                float # window shadows only on float 

# window rules https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc#rule
yabai -m rule --add app="^Music$" display=2
yabai -m rule --add app="^Microsoft Teams \(work or school\)$" display=2 
yabai -m rule --add app="^Microsoft Teams classic$" display=2
yabai -m rule --add app="^Discord$" display=2 
yabai -m rule --add app="^Singlebox Plus$" display=2 
yabai -m rule --add app="^Messages$" display=2
yabai -m rule --add app="^System Preferences$" manage=off 
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^iTerm2$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^Notes$" manage=off
yabai -m rule --add app="^1Password$" manage=off

# signals
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

## Use correct sketchybar height regardless of resolution -- automatic resizing
## https://github.com/FelixKratz/SketchyBar/discussions/12?sort=new#discussioncomment-6225020 
yabai -m signal --add event=display_resized action="brew services restart sketchybar"
