---
- hosts: localhost

  tasks:

    - name: Install base packages
      pacman:
        name:
          - rofi
          - zsh
          - kitty
          - python-pip
          - python2-pip
          - gcc
          - manjaro-settings-manager
          - github-cli
          - discord
          - steam-manjaro
          - python-pywal
          - xarchiver
          - zip
          - blueman
          - pulseaudio-bluetooth
          - playerctl
      become: yes
      become_user: root

    - name: Remove base packages
      pacman:
        name:
          - palemoon-bin
          - bmenu
        state: removed
      become: yes
      become_user: root

    - name: Install aur packages
      kewlfft.aur.aur:
        name: 
          - spotify
          - google-chrome
          - polybar

    - name: Install pip packages
      pip:
        name: grip


    ### System Files ### 

    - name: Enable colors
      replace:
        path: /etc/pacman.conf
        regexp: "#Color"
        replace: "Color"
      become: yes
      become_user: root

    - name: Pacman ILoveCandy
      lineinfile:
        dest: /etc/pacman.conf
        insertafter: "Color"
        line: 'ILoveCandy'
      become: yes
      become_user: root

    - name: Disable mouse acceleration
      copy:
        src: ~/.config/poof/sysfiles/50-mouse-acceleration.conf
        dest: /etc/X11/xorg.conf.d/50-mouse-acceleration.conf
      become: yes
      become_user: root

    - name: Disable beep sounds
      copy:
        src: ~/.config/poof/sysfiles/nobeep.conf
        dest: /etc/modprobe.d/nobeep.conf
      become: yes
      become_user: root
    
    - name: Set keybindings
      copy:
        src: ~/.config/poof/sysfiles/keyboard
        dest: /etc/default/keyboard
      become: yes
      become_user: root
          
