---
- hosts: localhost
  become: true
  become_user: davay

  tasks:
    - user:
        name: davay
        state: present

    - name: Install base packages
      pacman:
        name:
          - rofi
          - zsh
          - kitty
          - pulseaudio
          - pavucontrol
          - yay

    - name: Install aur packages
      aur:
        name: 
          - spotify
          - 

    - name: Enable colors
      replace:
        path: /etc/pacman.conf
        regexp: '#Color'
        replace: "Color"
      become: yes
      become_user: root




