---
- hosts: localhost

  tasks:

    - name: Install base packages
      pacman:
        name:
          - rofi
          - zsh
          - kitty
          - python-pip
          - python2-pip
          - gcc
          - manjaro-settings-manager
          - github-cli
          - discord
          - steam-manjaro
          - python-pywal
          - xarchiver
          - jq
          - zip
          - blueman
          - pulseaudio-bluetooth
          - dbus-python
          - playerctl
          - neofetch
          - lolcat
          - pavucontrol
          - xsettingsd
      become: yes
      become_user: root

    - name: Remove base packages
      pacman:
        name:
          - palemoon-bin
          - bmenu
        state: removed
      become: yes
      become_user: root

    - name: Install aur packages
      kewlfft.aur.aur:
        name: 
          - spotify
          - google-chrome
          - polybar
          - openrgb-git
          - otf-apple-sf-mono
          - otf-apple-sf-pro
          - otf-font-awesome-5-free
          - otf-ipafont
          - teamviewer
          - wpgtk-git
          - gtk-theme-flat-color-git
          - spicetify-cli-git
          - spicetify-themes-git
          - betterdiscordctl-git
          - pywal-discord-git
          - vmware-workstation

    - name: Install pip packages
      pip:
        name: grip

    ### System Files ### 

    - name: Enable colors
      replace:
        path: /etc/pacman.conf
        regexp: "#Color"
        replace: "Color"
      become: yes
      become_user: root

    - name: Pacman ILoveCandy
      lineinfile:
        dest: /etc/pacman.conf
        insertafter: "Color"
        line: 'ILoveCandy'
      become: yes
      become_user: root

    - name: Disable mouse acceleration
      copy:
        src: ~/.config/poof/sysfiles/50-mouse-acceleration.conf
        dest: /etc/X11/xorg.conf.d/50-mouse-acceleration.conf
      become: yes
      become_user: root

    - name: Disable beep sounds
      copy:
        src: ~/.config/poof/sysfiles/nobeep.conf
        dest: /etc/modprobe.d/nobeep.conf
      become: yes
      become_user: root
    
    - name: Set keybindings
      copy:
        src: ~/.config/poof/sysfiles/keyboard
        dest: /etc/default/keyboard
      become: yes
      become_user: root
        
    - name: Copy udev rules for OpenRGB
      copy:
        src: ~/.config/poof/sysfiles/60-openrgb.rules
        dest: /etc/udev/rules.d/60-openrgb.rules
      become: yes
      become_user: root

    - name: Copy color.ini to Spotify Turntable theme
      copy:
        src: ~/.config/poof/sysfiles/color.ini
        dest: /usr/share/spicetify-cli/Themes/Turntable/color.ini
      become: yes
      become_user: root

