---
- hosts: localhost

  tasks:

    - name: Install base packages
      pacman:
        name:
          - rofi
          - zsh
          - kitty
          - python-pip
          - python2-pip
          - gcc
      become: yes
      become_user: root

    - name: Install aur packages
      kewlfft.aur.aur:
        name: 
          - spotify
          - google-chrome
          - evhz-git

    - name: Install pip packages
      pip:
        name: grip #mb delete

    ### System Files ### 

    - name: Enable colors
      replace:
        path: /etc/pacman.conf
        regexp: '#Color'
        replace: "Color"
      become: yes
      become_user: root

    - name: Pacman ILoveCandy
      lineinfile:
        dest: /etc/pacman.conf
        line: 'ILoveCandy'
      become: yes
      become_user: root

    - name: Disable mouse acceleration
      copy:
        src: ~/.config/poof/sysfiles/50-mouse-acceleration.conf
        dest: /etc/X11/xorg.conf.d/50-mouse-acceleration.conf
      become: yes
      become_user: root
