---
- hosts: localhost

  tasks:

    - name: Install base packages
      pacman:
        name:
          - rofi
          - zsh
          - kitty
          - python-pip
          - python2-pip
      become: yes
      become_user: root

    - name: Install aur packages
      kewlfft.aur.aur:
        name: 
          - spotify
          - google-chrome

    - name: Install pip packages
      pip:
        name: grip

    - name: Enable colors
      replace:
        path: /etc/pacman.conf
        regexp: '#Color'
        replace: "Color"
      become: yes
      become_user: root

    - name: Pacman ILoveCandy
      lineinfile:
        dest: /etc/pacman.conf
        line: 'ILoveCandy'
      become: yes
      become_user: root



