#!/usr/bin/env sh

source "$HOME/.config/sketchybar/colors.sh" # Loads all defined colors
source "$HOME/.config/sketchybar/icons.sh"  # Loads all defined icons

PLUGIN_DIR="$HOME/.config/sketchybar/plugins"                 # Directory where all the plugin scripts are stored
FONT="SF Pro"                                                 # Needs to have Regular, Bold, Semibold, Heavy and Black variants
SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null" # The script that is run for clicking on space components
PADDINGS=2                                                    # All paddings use this value (icon, label, background and bar paddings)
POPUP_BORDER_WIDTH=2
POPUP_CORNER_RADIUS=11
SHADOW=on

# Setting up the general bar appearance and default values
sketchybar --bar height=28 \
    position=top \
    margin=7 \
    padding_left=10 \
    padding_right=10 \
    color="0x00000000" \
    y_offset=7 \
    shadow=$SHADOW \
    --default drawing=on \
    updates=when_shown \
    label.font="$FONT:Semibold:13.0" \
    icon.font="$FONT:Bold:14.0" \
    icon.color=$ICON_COLOR \
    label.color=$LABEL_COLOR \
    icon.padding_left=$PADDINGS \
    icon.padding_right=$PADDINGS \
    label.padding_left=$PADDINGS \
    label.padding_right=$PADDINGS \
    background.padding_right=$PADDINGS \
    background.padding_left=$PADDINGS \
    popup.background.border_width=$POPUP_BORDER_WIDTH \
    popup.background.corner_radius=$POPUP_CORNER_RADIUS \
    popup.background.border_color=$POPUP_BORDER_COLOR \
    popup.background.color=$POPUP_BACKGROUND_COLOR \
    popup.background.shadow.drawing=$SHADOW

# Left
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

for i in "${!SPACE_ICONS[@]}"; do
    sid=$(($i + 1))
    sketchybar --add space space.$sid left \
        --set space.$sid associated_space=$sid \
        icon=${SPACE_ICONS[i]} \
        icon.padding_left=22 \
        icon.padding_right=22 \
        icon.highlight_color=$RED \
        background.padding_left=-8 \
        background.padding_right=-8 \
        background.height=26 \
        background.corner_radius=9 \
        background.color=0xff3C3E4F \
        background.drawing=on \
        label.drawing=off \
        click_script="$SPACE_CLICK_SCRIPT"
done

# sketchybar --add item separator left \
#     --set separator icon= \
#     icon.font="Hack Nerd Font:Regular:16.0" \
#     background.padding_left=26 \
#     background.padding_right=15 \
#     label.drawing=off \
#     icon.color=$WHITE
#
sketchybar --add event window_focus \
    --add item system.yabai left \
    --set system.yabai script="$PLUGIN_DIR/yabai.sh" \
    icon.font="$FONT:Regular:16.0" \
    label.drawing=off \
    icon.color=$GREEN \
    updates=on \
    --subscribe system.yabai window_focus mouse.clicked \
    \
    --add item front_app left \
    --set front_app script="$PLUGIN_DIR/front_app.sh" \
    icon.drawing=off \
    background.padding_left=0 \
    label.color=$WHITE \
    label.font="$FONT:Regular:14.0" \
    --subscribe front_app front_app_switched

# Right
sketchybar --add item calendar right \
    --set calendar update_freq=15 \
    icon=cal \
    icon.font="$FONT:Black:12.0" \
    icon.padding_left=15 \
    label.width=55 \
    label.align=right \
    label.padding_right=15 \
    align=center \
    script="$PLUGIN_DIR/time.sh" \
    background.color=0x00000000 \
    background.height=26 \
    background.corner_radius=11

### Script is broken with recurring events 
# sketchybar -m --add item upcoming right \
#     --set upcoming update_freq=20 \
#     --set upcoming updates=on \
#     --set upcoming popup.background.color=0xff000000 \
#     --set upcoming popup.height=20 \
#     --set upcoming script="python3 $PLUGIN_DIR/upcoming.py" \
#     --set upcoming click_script="sketchybar -m --set upcoming popup.drawing=toggle"

sketchybar --add item spot right \
    --set spot update_freq=1 \
    icon.drawing=off \
    updates=on \
    script="~/.config/sketchybar/plugins/spotify.sh" \
    background.padding_left=0 \
    label.font="FiraCode Nerd Font:Regular:12.0" \ 

############## FINALIZING THE SETUP ##############
sketchybar --update
